// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
// -----------------------------------------------------------------------------------------------------------------------------------------------------

RWTexture2D<float4> color_result;
// -----------------------------------------------------------------------------------------------------------------------------------------------------

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    color_result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
